title: Piráti České Budějovice
default_locale: "cs"
permalink: pretty
markdown: kramdown
facebookurl: https://www.facebook.com/PiratiCB
logo: /static/logo_cb3.svg

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
paginate: 8
paginate_path: "/clanky/:num/"
articlepath: blog
keywords: českobudějovicko,piráti,budějovice,budějce
url: https://cb.pirati.cz
